name: traveldart
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Local Database
  isar: ^3.1.0
  ## https://github.com/MrLittleWhite/isar_flutter_libs
  isar_flutter_libs:
    git:
      url: https://github.com/MrLittleWhite/isar_flutter_libs.git
  # 로컬 DB 위치 주입
  path_provider: ^2.1.5

  # StateManagement
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.6.1

  # Model
  freezed_annotation: ^2.4.4

  # Routing
  go_router: ^14.4.1

  # 로거
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  custom_lint: ^0.7.0
  # Generated
  build_runner: ^2.4.13

  # StateManagement
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2

  # Modeling
  freezed: ^2.5.7

  # Routing
  go_router_builder: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/
